{% set name = "python-calamine" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/python_calamine-{{ version }}.tar.gz
  sha256: 4171fadf4a2db1b1ed84536fb2f16ea14bde894d690ff321a85e27df26286b37

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  missing_dso_whitelist:
    - "$RPATH/ld64.so.1"  # [s390x]
  skip: True  # [py<38]

requirements:
  build:
    - {{ compiler("rust") }}
    - {{ compiler("c") }}
    - cargo-bundle-licenses
  host:
    - python
    - pip
    - poetry-core
    - maturin >=1,<2
  run:
    - python
    - packaging >=24.1,<25

test:
  source_files:
    - tests
  imports:
    - python_calamine
  commands:
    - pip check
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/dimastbk/python-calamine
  summary: Python binding for Rust's library for reading excel and odf file - calamine.
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  doc_url: https://github.com/dimastbk/python-calamine/blob/master/README.md
  dev_url: https://github.com/dimastbk/python-calamine
  description: Python binding for beautiful Rust's library for reading excel and odf file - calamine.

extra:
  recipe-maintainers:
    - dimastbk
